CARGO_COL_CANDIDATES = ["CARGO", "CARGOS", "IMPORTE", "DEBITO", "DÉBITO", "RETIRO"]

FECHA_COL_CANDIDATES = [
    "FECHA", "FECHA OPERACION", "FECHA DE OPERACION",
    "FECHA MOV", "FECHA_MOV", "FECHA CONTABLE", "FECHA FACTURA"
]

DESCRIP_COL_CANDIDATES = [
    "DESCRIPCION", "DESCRIPCIÓN", "CONCEPTO", "REFERENCIA", "DETALLE"
]

EGRESO_MONTO_CANDIDATES = ["TOTAL", "MONTO", "IMPORTE"]

EGRESO_FECHA_CANDIDATES = [
    "FECHA", "FECHA EGRESO", "FECHA_EMISION", "FECHA EMISION"
]

EGRESO_CONCEPTO_CANDIDATES = [
    "CONCEPTO", "DESCRIPCION", "DESCRIPCIÓN", "PROVEEDOR", "REFERENCIA"
]

INGRESO_ID_CANDIDATES = [
    "FOLIO", "FOLIO FACTURA", "FACTURA", "NO_FACTURA", "NUM_DOCUMENTO"
]
